# Generated by Django 5.0.7 on 2024-07-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                default="assets/img/avatar.png", upload_to="images/users/"
            ),
        ),
    ]
