# Generated by Django 5.0.7 on 2024-07-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="date_post",
            field=models.DateField(auto_now_add=True),
        ),
    ]
