# Generated by Django 5.0.7 on 2024-07-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0002_alter_problem_date_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="titreProbleme",
            field=models.TextField(),
        ),
    ]
