# Generated by Django 5.0.7 on 2024-07-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0002_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="province",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
