# Generated by Django 5.0.7 on 2024-07-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0003_alter_problem_titreprobleme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                default="static/assets/img/avatar.png", upload_to="images/users/"
            ),
        ),
    ]
