# Generated by Django 5.0.7 on 2024-07-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0003_userprofile_city_userprofile_province_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Femme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menage",
                    models.CharField(
                        choices=[
                            ("Bushwira", "Bushwira"),
                            ("Mbobero", "Mbobero"),
                            ("Kagabi", "Kagabi"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "appliquer_questionnaire",
                    models.CharField(
                        choices=[
                            ("1ère fois", "1ère fois"),
                            ("2e fois", "2e fois"),
                            ("3e fois", "3e fois"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name_femme", models.CharField(max_length=100)),
                ("numero_tel_femme", models.CharField(max_length=20)),
                (
                    "form_file",
                    models.ImageField(blank=True, null=True, upload_to="femme_images/"),
                ),
                ("age_femme", models.IntegerField()),
                (
                    "scolarite_femme",
                    models.CharField(
                        choices=[
                            ("Jamais scolarisée", "Jamais scolarisée"),
                            ("Primaire", "Primaire"),
                            ("Secondaire", "Secondaire"),
                            ("Universitaire/Supérieur", "Universitaire/Supérieur"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
