# Generated by Django 5.0.7 on 2024-07-22 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0004_femme"),
    ]

    operations = [
        migrations.AddField(
            model_name="femme",
            name="descriptionCasFemme",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="femme",
            name="genreProbleme",
            field=models.CharField(
                choices=[
                    ("Financier", "Financier"),
                    ("Social", "Social"),
                    ("Culturel", "Culturel"),
                    ("Grossesse", "Grossesse"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="femme",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
