# Generated by Django 5.0.7 on 2024-07-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0004_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beneficiary", models.CharField(max_length=255)),
                ("date_action", models.DateField()),
                ("description_action", models.TextField()),
                (
                    "cost_estimated",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("Infrascture", "Infrascture"),
                            ("soutien-cas-violence", "Soutien cas de violence"),
                            ("incendie", "Incendie"),
                            ("formation", "Formation"),
                            ("construction-batiment", "Construction Batiment"),
                            ("construction-route", "Construction Routes"),
                            ("autres-dons", "Autres dons"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
