# Generated by Django 5.0.7 on 2024-07-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0005_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="image_actions",
            field=models.ImageField(blank=True, null=True, upload_to="actions/"),
        ),
    ]
