# Generated by Django 5.0.7 on 2024-07-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0005_femme_descriptioncasfemme_femme_genreprobleme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="femme",
            name="titleCase",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
