# Generated by Django 5.0.7 on 2024-07-23 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0006_femme_titlecase"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre_probleme",
                    models.CharField(
                        choices=[
                            ("Financier", "Financier"),
                            ("Social", "Social"),
                            ("Culturel", "Culturel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_probleme", models.DateField()),
                ("time_probleme", models.TimeField()),
                ("description_cas_probleme", models.TextField()),
                (
                    "province_cas_probleme",
                    models.CharField(
                        choices=[
                            ("Bukavu", "Bukavu"),
                            ("Kabare", "Kabare"),
                            ("Walungu", "Walungu"),
                            ("Fizi", "Fizi"),
                            ("Mwenga", "Mwenga"),
                        ],
                        max_length=20,
                    ),
                ),
                ("precision_endroit_probleme", models.CharField(max_length=255)),
                ("anticipation_aide", models.TextField()),
                ("acteur_cause_probleme", models.CharField(max_length=255)),
                ("appliquer_questionnaire", models.TextField()),
                ("presumes_acteurs", models.TextField()),
                ("problem_victiomes", models.TextField()),
                ("consequences_problemes", models.TextField()),
                (
                    "images_preuves_probleme",
                    models.ImageField(
                        blank=True, null=True, upload_to="problem_images/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
