# Generated by Django 5.0.7 on 2024-07-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0006_action_image_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(default="Null", max_length=50, null=True),
        ),
    ]
