# Generated by Django 5.0.7 on 2024-07-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0007_userprofile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="adresse",
            field=models.TextField(default="Not defined"),
        ),
    ]
