# Generated by Django 5.0.7 on 2024-07-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0008_userprofile_adresse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
