# Generated by Django 5.0.7 on 2024-07-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0009_alter_userprofile_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sugestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.TextField()),
                ("message", models.TextField()),
            ],
        ),
    ]
